apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: fagtorsdag-web
  namespace: fagtorsdag
  labels:
    team: fagtorsdag
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1001"
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  envFrom:
    - secret: fagtorsdag-trello-secrets
  liveness:
    path: /api/healthy
  readiness:
    path: /api/healthy
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
