apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: reops-solan
  namespace: team-researchops
  labels:
    team: team-researchops
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1001"
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  envFrom:
    - secret: solan-trello-secrets
  liveness:
    path: /internal/is-alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is-ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  accessPolicy:
    outbound:
      external:
        - host: api.trello.com
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
